from datetime import datetime
import random
from io import BytesIO

from fpdf import FPDF
from num2words import num2words

from src.schemas import OrderCreate

def create_invoice(order: OrderCreate):
    # Calculate totals
    subtotal = sum(item.quantity * item.price for item in order.items)
    cgst = subtotal * 0.05  # 5% CGST
    sgst = subtotal * 0.05  # 5% SGST
    total_tax = cgst + sgst
    total = subtotal + total_tax

    # Generate invoice number (e.g., JS-2025-001)
    invoice_number = f"JS-{datetime.now().year}-{random.randint(100, 999):03d}"

    # Generate PDF
    pdf = FPDF()
    pdf.add_page()

    # Add Unicode font (ensure DejaVuSans.ttf is in the project directory)
    pdf.add_font("DejaVuSans", "", "DejaVuSans.ttf", uni=True)
    pdf.add_font("DejaVuSans", "B", "DejaVuSans.ttf", uni=True)
    pdf.add_font("DejaVuSans", "I", "DejaVuSans.ttf", uni=True)

    # Draw a border around the invoice
    pdf.set_line_width(0.5)
    pdf.rect(5, 5, 200, 287)  # A4 size: 210x297mm, 5mm margin

    # Header: Company Details
    pdf.set_font("DejaVuSans", 'B', 16)
    pdf.cell(0, 10, "JungleSmart", ln=1, align='C')
    pdf.set_font("DejaVuSans", '', 10)
    pdf.cell(0, 6, "123 Main St, City, Country", ln=1, align='C')
    pdf.cell(0, 6, "GSTIN: 12ABCDE3456F7ZH", ln=1, align='C')
    pdf.cell(0, 6, "Phone: +91 98765 43210 | Email: info@junglesmart.com", ln=1, align='C')
    pdf.ln(5)

    # Title
    pdf.set_font("DejaVuSans", 'B', 14)
    pdf.cell(0, 10, "Tax Invoice", ln=1, align='C')
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())  # Horizontal line
    pdf.ln(5)

    # Invoice Details (Left) and Date (Right)
    pdf.set_font("DejaVuSans", '', 10)
    pdf.cell(90, 6, f"Invoice No: {invoice_number}", ln=0)
    pdf.cell(90, 6, f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=1, align='R')
    pdf.cell(90, 6, "Place of Supply: City, Country", ln=0)
    pdf.ln(5)

    # Customer Details
    pdf.set_font("DejaVuSans", 'B', 10)
    pdf.cell(0, 6, "Bill To:", ln=1)
    pdf.set_font("DejaVuSans", '', 10)
    pdf.cell(0, 6, f"Name: {order.customer_name}", ln=1)
    pdf.cell(0, 6, f"Email: {order.customer_email}", ln=1)
    pdf.cell(0, 6, "Address: 456 Customer Lane, City, Country", ln=1)
    pdf.cell(0, 6, "GSTIN: 22XYZAB1234C5DE", ln=1)
    pdf.ln(5)

    # Item Table (Total width = 190mm)
    pdf.set_font("DejaVuSans", 'B', 10)
    pdf.cell(20, 10, "Sl No", border=1)
    pdf.cell(60, 10, "Item", border=1)
    pdf.cell(30, 10, "HSN/SAC", border=1)
    pdf.cell(25, 10, "Quantity", border=1)
    pdf.cell(25, 10, "Price", border=1)
    pdf.cell(30, 10, "Total", border=1)
    pdf.ln()

    pdf.set_font("DejaVuSans", '', 10)
    for idx, item in enumerate(order.items, 1):
        pdf.cell(20, 8, str(idx), border=1)
        pdf.cell(60, 8, item.name, border=1)
        pdf.cell(30, 8, item.hsn_code, border=1)
        pdf.cell(25, 8, str(item.quantity), border=1)
        pdf.cell(25, 8, f"₹{item.price:.2f}", border=1)
        pdf.cell(30, 8, f"₹{item.quantity * item.price:.2f}", border=1)
        pdf.ln()

    # Totals Section (Aligned to table width)
    pdf.ln(5)
    pdf.set_font("DejaVuSans", 'B', 10)
    pdf.cell(160, 8, "Subtotal", align='R')
    pdf.cell(30, 8, f"₹{subtotal:.2f}", border=1, ln=1, align='R')
    pdf.cell(160, 8, "CGST (5%)", align='R')
    pdf.cell(30, 8, f"₹{cgst:.2f}", border=1, ln=1, align='R')
    pdf.cell(160, 8, "SGST (5%)", align='R')
    pdf.cell(30, 8, f"₹{sgst:.2f}", border=1, ln=1, align='R')
    pdf.cell(160, 8, "Total", align='R')
    pdf.cell(30, 8, f"₹{total:.2f}", border=1, ln=1, align='R')

    # Amount in Words (Stretched to table width)

    total_in_words = num2words(int(total)).capitalize() + " Rupees Only"
    pdf.ln(5)
    pdf.set_font("DejaVuSans", '', 10)
    pdf.cell(0, 6, f"Amount in Words: {total_in_words}", border=1, ln=1)

    # Terms and Conditions
    pdf.ln(5)
    pdf.set_font("DejaVuSans", 'B', 10)
    pdf.cell(0, 6, "Terms & Conditions:", ln=1)
    pdf.set_font("DejaVuSans", '', 8)
    pdf.cell(0, 5, "1. Payment due within 30 days.", ln=1)
    pdf.cell(0, 5, "2. Goods once sold will not be taken back.", ln=1)
    pdf.cell(0, 5, "3. All disputes are subject to City jurisdiction.", ln=1)

    # Signature Section
    pdf.ln(10)
    pdf.set_font("DejaVuSans", 'B', 10)
    pdf.cell(0, 6, "For JungleSmart", ln=1, align='R')
    pdf.set_font("DejaVuSans", '', 8)
    pdf.cell(0, 5, "Authorized Signatory", ln=1, align='R')
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=1, align='R')

    # Footer
    pdf.set_y(-30)
    pdf.set_font("DejaVuSans", 'I', 8)
    pdf.cell(0, 5, "Thank you for your business!", ln=1, align='C')
    pdf.cell(0, 5, "Generated by JungleSmart Billing System | Empowering Wealth Creation", ln=1, align='C')

    # Convert bytearray to bytes and return
    pdf_bytes = bytes(pdf.output(dest="S").encode("latin1"))
    return pdf_bytes
